version: '3'
networks:
  network:
    driver: bridge
services:
  consul:
    image: "grovemountain/consul:1.6.0-beta3"
    ports:
      - "8500:8500"
    volumes:
      - "./envoy_demo.hcl:/consul/config/envoy_demo.hcl" 
    restart: always
    networks:
    - network
  picture-service:
    image: "grovemountain/picture-service:latest"
    ports:
      - "8080:8080"
      - "19000:19000"
    restart: always
    networks:
    - network
  consul-demo-gateway:
    image: "grovemountain/consul-demo-gateway:latest"
    ports:
      - "8000:8000"
#      - "19001:19000"
    volumes:
      - "./static/holy_grail.json:/app/static/holy_grail.json"
    restart: always
    networks:
    - network
  consul-template:
    image: "hashicorp/consul-template:latest"
    command: "-template /static/in.tpl:/static/holy_grail.json -consul-addr consul:8500"
    volumes:
      - "./static:/static"
    restart: always
    networks:
    - network
  picture-proxy:
    image: "grovemountain/consul-envoy:1.6.0-beta3-v1.11.0"
    entrypoint: "/wait_for_consul.sh"
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    command: "consul connect envoy -sidecar-for picture-service"
    network_mode: "service:picture-service"
  client-proxy:
    image: "grovemountain/consul-envoy:1.6.0-beta3-v1.11.0"
    entrypoint: "/wait_for_consul.sh"
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    command: "consul connect envoy -sidecar-for client"
    network_mode: "service:consul-demo-gateway"
